require('config.lspkind')
-- require('config.tree-sitter')
require('config.colorscheme')
require('gitsigns').setup()
require('statusline.evil_lualine')
require('config.compe')
require('nvim_comment').setup()
require('colorizer').setup()
require('config.quick-scope')
